version: '3'
services:
  api-server:
    build: ./
    env_file: ./config/.env
    ports:
      - '3000:3000'
    networks:
      - storybooksdocker-app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6-xenial
    environment:
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - '27017:27017'
    networks:
      - storybooksdocker-app
    volumes:
      - mongo-data:/data/db

networks:
  storybooksdocker-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
